In [ ]:
import numpy as np
import pandas as pd

# mount google drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
# read all data
X_train_keybert = pd.read_csv('/content/drive/My Drive/BT4222 group project/final_data/x_train_keybert.csv')
X_test_keybert = pd.read_csv('/content/drive/My Drive/BT4222 group project/final_data/x_test_keybert.csv')

X_train_topics = pd.read_csv('/content/drive/My Drive/BT4222 group project/final_data/X_train_topics.csv')
X_test_topics = pd.read_csv('/content/drive/My Drive/BT4222 group project/final_data/X_test_topics.csv')

y_train = pd.read_csv('/content/drive/My Drive/BT4222 group project/final_data/y_train.csv')
y_test = pd.read_csv('/content/drive/My Drive/BT4222 group project/final_data/y_test.csv')

X_train_keybert.shape, X_test_keybert.shape, X_train_topics.shape, X_test_topics.shape, y_train.shape, y_test.shape

((58181, 1113),
 (14546, 1113),
 (58181, 1094),
 (14546, 1094),
 (58181, 1),
 (14546, 1))

# Data exploration and pre-processing

In [ ]:
X_train_keybert.head(3)

,title,release_year,end_year,type,runtime,Action,Adult,Adventure,Animation,Biography,...,Keyword_town,Keyword_travel,Keyword_village,Keyword_war,Keyword_wedding,Keyword_wife,Keyword_woman,Keyword_writer,Keyword_york,Keyword_young
0,Couple in a Hole,2015,NaN,0,105.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,You're Telling Me!,1934,NaN,0,66.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,The Giant Spider Invasion,1975,NaN,0,84.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
X_train_topics.head(3)

,Unnamed: 0,title,release_year,end_year,type,runtime,Action,Adult,Adventure,Animation,...,x0_topic_72,x0_topic_73,x0_topic_74,x0_topic_75,x0_topic_76,x0_topic_77,x0_topic_78,x0_topic_79,x0_topic_8,x0_topic_9
0,0,Couple in a Hole,2015,NaN,0,105.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,You're Telling Me!,1934,NaN,0,66.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,The Giant Spider Invasion,1975,NaN,0,84.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
x_train_keybert = X_train_keybert.drop(X_train_keybert.columns[[0, 2]], axis=1)
x_test_keybert = X_test_keybert.drop(X_test_keybert.columns[[0, 2]], axis=1)
x_train_topics = X_train_topics.drop(X_train_topics.columns[[0, 1, 3]], axis=1)
x_test_topics = X_test_topics.drop(X_test_topics.columns[[0, 1, 3]], axis=1)
x_train_keybert.shape, x_test_keybert.shape, x_train_topics.shape, x_test_topics.shape

((58181, 1111), (14546, 1111), (58181, 1091), (14546, 1091))

In [ ]:
x_train_keybert.head()

,release_year,type,runtime,Action,Adult,Adventure,Animation,Biography,Comedy,Crime,...,Keyword_town,Keyword_travel,Keyword_village,Keyword_war,Keyword_wedding,Keyword_wife,Keyword_woman,Keyword_writer,Keyword_york,Keyword_young
0,2015,0,105.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,1934,0,66.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,1975,0,84.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,2011,0,102.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
4,1973,0,118.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
x_train_topics.head()

,release_year,type,runtime,Action,Adult,Adventure,Animation,Biography,Comedy,Crime,...,x0_topic_72,x0_topic_73,x0_topic_74,x0_topic_75,x0_topic_76,x0_topic_77,x0_topic_78,x0_topic_79,x0_topic_8,x0_topic_9
0,2015,0,105.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1934,0,66.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1975,0,84.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2011,0,102.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1973,0,118.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Feature selection using linear regression

### Feature selection on the data from keybert

In [ ]:
from sklearn.datasets import make_regression
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
import operator
 
# feature selection
def select_features(X_train, y_train, X_test):
	# configure to select all features
	fs = SelectKBest(score_func=f_regression, k='all')
	# learn relationship from training data
	fs.fit(X_train, y_train)
	# transform train input data
	X_train_fs = fs.transform(X_train)
	# transform test input data
	X_test_fs = fs.transform(X_test)
	return X_train_fs, X_test_fs, fs
 
# feature selection
X_train_fs, X_test_fs, fs = select_features(x_train_keybert, y_train, x_test_keybert)

all_features = {}
for i in range(len(fs.scores_)):
  all_features[list(x_train_keybert.columns)[i]] = fs.scores_[i]

sorted_d = dict(sorted(all_features.items(), key=operator.itemgetter(1),reverse=True))
# print(sorted_d)
# write to csv
feature_scores_keybert = pd.DataFrame([sorted_d]) 
feature_scores_keybert.to_csv(r'/content/drive/My Drive/BT4222 group project/final_data/feature_scores_keybert.csv', index = False)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

### Feature selection on the data from topic modelling

In [ ]:
# feature selection
X_train_fs, X_test_fs, fs = select_features(x_train_topics, y_train, x_test_topics)

all_features = {}
for i in range(len(fs.scores_)):
  all_features[list(x_train_topics.columns)[i]] = fs.scores_[i]

sorted_d = dict(sorted(all_features.items(), key=operator.itemgetter(1),reverse=True))
sorted_d
# write to csv
feature_scores_topics = pd.DataFrame([sorted_d]) 
feature_scores_topics.to_csv(r'/content/drive/My Drive/BT4222 group project/final_data/feature_scores_topics.csv', index = False)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)